development:
  adapter: mysql2
  host: localhost
  encoding: utf8
  pool: 10
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: development<%= ENV['TEST_ENV_NUMBER'] %>
  socket: /var/run/mysqld/mysqld.sock
  encryption_key: cdaed00f0161582218638cb5493c1b1e0a59e022eb9f01cce8ff5ab1d1baddde072d9e12a67ca713d39258f5ce0cc518e404497e9f6aa68ada3ad21b2d2b64ed
test:
  adapter: mysql2
  host: localhost
  encoding: utf8
  pool: 10
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  socket: /var/run/mysqld/mysqld.sock
  encryption_key: d1a99b6befcc188fb8a6a8b3e40c5439ae9d7dbbe73254c76504f150c5cbcabc42bed0465bd7336e7822bacb92829d75e72b3674bed18fc9212d76f0f8b17650
